// Generated by CoffeeScript 1.9.2
(function() {
  var Amostra;

  Amostra = (function() {
    function Amostra() {}

    Amostra.numero;

    Amostra.exame;

    Amostra.resultado;

    Amostra.criado_em;

    Amostra.resultado_em;

    Amostra.normal;

    return Amostra;

  })();

}).call(this);
