// Generated by CoffeeScript 1.9.2
(function() {
  var Amostra,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Amostra = (function() {
    var resultadoProntoList;

    function Amostra(id, exame, lote) {
      this.id = id;
      this.exame = exame;
      this.lote = lote;
      this.fireResultadoPronto = bind(this.fireResultadoPronto, this);
      this.criadoEm = new Date;
      this.status = 'aguardando';
      console.log('nova amostra ' + this.id + ' exame ' + this.exame.codigo);
    }

    Amostra.resultado;

    Amostra.resultadoEm;

    Amostra.normal;

    resultadoProntoList = [];

    Amostra.prototype.addResultadoPronto = function(f) {
      return resultadoProntoList.push(f);
    };

    Amostra.prototype.fireResultadoPronto = function() {
      var f, i, len, results;
      this.status = 'pronto';
      console.log('resultado pronto amostra ' + this.id);
      results = [];
      for (i = 0, len = resultadoProntoList.length; i < len; i++) {
        f = resultadoProntoList[i];
        results.push(f());
      }
      return results;
    };

    Amostra.prototype.iniciarProcessamento = function() {
      this.status = 'processo';
      return console.log('amostra em processo ' + this.id);
    };

    return Amostra;

  })();

  root.Amostra = Amostra;

}).call(this);
