// Generated by CoffeeScript 1.9.2
(function() {
  var TipoExame;

  TipoExame = (function() {
    function TipoExame() {}

    TipoExame.codigo;

    TipoExame.nome;

    TipoExame.tipo;

    TipoExame.minimoPossivel;

    TipoExame.maximoPossivel;

    TipoExame.minimoNormal;

    TipoExame.maximoNormal;

    TipoExame.prototype.resultadoNormal = function(resultado) {};

    return TipoExame;

  })();

  root.TipoExame = TipoExame;

}).call(this);
