// Generated by CoffeeScript 1.9.2
(function() {
  var TipoExame;

  TipoExame = (function() {
    function TipoExame() {}

    TipoExame.codigo;

    TipoExame.nome;

    TipoExame.tipo;

    TipoExame.minimo_possivel;

    TipoExame.maximo_possivel;

    TipoExame.minimo_normal;

    TipoExame.maximo_normal;

    return TipoExame;

  })();

}).call(this);
